env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
language:
  node_js
node_js:
  - "8"
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE travis_test;" -U postgres
  - psql -c "CREATE USER dbuser with password '12345678';" -U postgres
install:
  - cd backend
  - npm install --save bcrypt-nodejs && npm uninstall --save bcrypt
script:
  - npm test